### ISSUE TITLE
Why only port 80?

### ISSUE THREAD

**Issue by javoire** [madwire/tutum-nginx-proxy#9]
Hey! I'm using this and it works great. But why do the apps have to listen on port 80 internally and not any port?

Cheers

**Comment by madwire** [comment]
It's because this container auto reconfigures its self on any of the following reported changes from tutum (Scaling, Redeploying, Stopping, Starting, Terminating). So to limit when it actually restarts Nginx I'm checking to see if the reported service is a web based service and not a DB for example. The must logical port was 80/443. PR are welcome if you want to make it configurable. But bare in mind that it will be set for all services you run.
